version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r PhotoAlbum-Lambdas/index_photo_lambda/requirements.txt -t ./package
  build:
    commands:
      - cp PhotoAlbum-Lambdas/index_photo_lambda/lambda_function.py ./package/
      - cd PhotoAlbum-Lambdas/index_photo_lambda/package && zip -r ../index-photo.zip .
artifacts:
  files:
    - PhotoAlbum-Lambdas/index_photo_lambda/index-photo.zip
