version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r PhotoAlbum-Lambdas/search_photo_lambda/requirements.txt -t ./package
  build:
    commands:
      - cp PhotoAlbum-Lambdas/search_photo_lambda/lambda_function.py ./package/
      - cd PhotoAlbum-Lambdas/search_photo_lambda/package && zip -r ../search-photos.zip .
artifacts:
  files:
    - search-photos.zip
